package cj.netos.uc.plugin.dao;

import cj.netos.uc.domain.AppAccount;
import cj.netos.uc.domain.AppAccountExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AppAccountMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_account
	 * @mbg.generated  Fri Sep 27 14:13:15 PHT 2019
	 */
	long countByExample(AppAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_account
	 * @mbg.generated  Fri Sep 27 14:13:15 PHT 2019
	 */
	int deleteByExample(AppAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_account
	 * @mbg.generated  Fri Sep 27 14:13:15 PHT 2019
	 */
	int deleteByPrimaryKey(String accountId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_account
	 * @mbg.generated  Fri Sep 27 14:13:15 PHT 2019
	 */
	int insert(AppAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_account
	 * @mbg.generated  Fri Sep 27 14:13:15 PHT 2019
	 */
	int insertSelective(AppAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_account
	 * @mbg.generated  Fri Sep 27 14:13:15 PHT 2019
	 */
	List<AppAccount> selectByExample(AppAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_account
	 * @mbg.generated  Fri Sep 27 14:13:15 PHT 2019
	 */
	AppAccount selectByPrimaryKey(String accountId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_account
	 * @mbg.generated  Fri Sep 27 14:13:15 PHT 2019
	 */
	int updateByExampleSelective(@Param("record") AppAccount record, @Param("example") AppAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_account
	 * @mbg.generated  Fri Sep 27 14:13:15 PHT 2019
	 */
	int updateByExample(@Param("record") AppAccount record, @Param("example") AppAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_account
	 * @mbg.generated  Fri Sep 27 14:13:15 PHT 2019
	 */
	int updateByPrimaryKeySelective(AppAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_account
	 * @mbg.generated  Fri Sep 27 14:13:15 PHT 2019
	 */
	int updateByPrimaryKey(AppAccount record);

	void updateAccountEnable(@Param(value = "accountid") String accountid, @Param(value = "enable") boolean enable);

    List<AppAccount> pageAccount(@Param(value = "appid") String tenantid, @Param(value = "currPage") int currPage, @Param(value = "pageSize") int pageSize);

    void updatePwd(@Param(value = "accountid") String accountid, @Param(value = "newpwd") String newpwd);
}