package cj.netos.uc.plugin.dao;

import cj.netos.uc.domain.AppMenu;
import cj.netos.uc.domain.AppMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppMenuMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_menu
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	long countByExample(AppMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_menu
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	int deleteByExample(AppMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_menu
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	int deleteByPrimaryKey(String menuId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_menu
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	int insert(AppMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_menu
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	int insertSelective(AppMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_menu
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	List<AppMenu> selectByExample(AppMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_menu
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	AppMenu selectByPrimaryKey(String menuId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_menu
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	int updateByExampleSelective(@Param("record") AppMenu record, @Param("example") AppMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_menu
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	int updateByExample(@Param("record") AppMenu record, @Param("example") AppMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_menu
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	int updateByPrimaryKeySelective(AppMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_menu
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	int updateByPrimaryKey(AppMenu record);
}