package cj.netos.uc.plugin.dao;

import cj.netos.uc.domain.AppRole;
import cj.netos.uc.domain.AppRoleExample;
import java.util.List;

import cj.netos.uc.domain.UcUser;
import org.apache.ibatis.annotations.Param;

public interface AppRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_role
	 * @mbg.generated  Fri Sep 27 14:13:15 PHT 2019
	 */
	long countByExample(AppRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_role
	 * @mbg.generated  Fri Sep 27 14:13:15 PHT 2019
	 */
	int deleteByExample(AppRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_role
	 * @mbg.generated  Fri Sep 27 14:13:15 PHT 2019
	 */
	int deleteByPrimaryKey(String roleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_role
	 * @mbg.generated  Fri Sep 27 14:13:15 PHT 2019
	 */
	int insert(AppRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_role
	 * @mbg.generated  Fri Sep 27 14:13:15 PHT 2019
	 */
	int insertSelective(AppRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_role
	 * @mbg.generated  Fri Sep 27 14:13:15 PHT 2019
	 */
	List<AppRole> selectByExample(AppRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_role
	 * @mbg.generated  Fri Sep 27 14:13:15 PHT 2019
	 */
	AppRole selectByPrimaryKey(String roleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_role
	 * @mbg.generated  Fri Sep 27 14:13:15 PHT 2019
	 */
	int updateByExampleSelective(@Param("record") AppRole record, @Param("example") AppRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_role
	 * @mbg.generated  Fri Sep 27 14:13:15 PHT 2019
	 */
	int updateByExample(@Param("record") AppRole record, @Param("example") AppRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_role
	 * @mbg.generated  Fri Sep 27 14:13:15 PHT 2019
	 */
	int updateByPrimaryKeySelective(AppRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_role
	 * @mbg.generated  Fri Sep 27 14:13:15 PHT 2019
	 */
	int updateByPrimaryKey(AppRole record);

	List<AppRole> pageRole(@Param(value = "appid") String appid, @Param(value = "currPage") int currPage, @Param(value = "pageSize") int pageSize);



}