package cj.netos.uc.plugin.dao;

import cj.netos.uc.domain.AppRole;
import cj.netos.uc.domain.AppRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_role
	 * @mbg.generated  Wed Aug 28 22:17:33 PHT 2019
	 */
	long countByExample(AppRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_role
	 * @mbg.generated  Wed Aug 28 22:17:33 PHT 2019
	 */
	int deleteByExample(AppRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_role
	 * @mbg.generated  Wed Aug 28 22:17:33 PHT 2019
	 */
	int deleteByPrimaryKey(String roleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_role
	 * @mbg.generated  Wed Aug 28 22:17:33 PHT 2019
	 */
	int insert(AppRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_role
	 * @mbg.generated  Wed Aug 28 22:17:33 PHT 2019
	 */
	int insertSelective(AppRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_role
	 * @mbg.generated  Wed Aug 28 22:17:33 PHT 2019
	 */
	List<AppRole> selectByExample(AppRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_role
	 * @mbg.generated  Wed Aug 28 22:17:33 PHT 2019
	 */
	AppRole selectByPrimaryKey(String roleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_role
	 * @mbg.generated  Wed Aug 28 22:17:33 PHT 2019
	 */
	int updateByExampleSelective(@Param("record") AppRole record, @Param("example") AppRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_role
	 * @mbg.generated  Wed Aug 28 22:17:33 PHT 2019
	 */
	int updateByExample(@Param("record") AppRole record, @Param("example") AppRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_role
	 * @mbg.generated  Wed Aug 28 22:17:33 PHT 2019
	 */
	int updateByPrimaryKeySelective(AppRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_role
	 * @mbg.generated  Wed Aug 28 22:17:33 PHT 2019
	 */
	int updateByPrimaryKey(AppRole record);
}