package cj.netos.uc.plugin.dao;

import cj.netos.uc.domain.PaMenu;
import cj.netos.uc.domain.PaMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pa_menu
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    long countByExample(PaMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pa_menu
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    int deleteByExample(PaMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pa_menu
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    int deleteByPrimaryKey(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pa_menu
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    int insert(PaMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pa_menu
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    int insertSelective(PaMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pa_menu
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    List<PaMenu> selectByExample(PaMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pa_menu
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    PaMenu selectByPrimaryKey(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pa_menu
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    int updateByExampleSelective(@Param("record") PaMenu record, @Param("example") PaMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pa_menu
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    int updateByExample(@Param("record") PaMenu record, @Param("example") PaMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pa_menu
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    int updateByPrimaryKeySelective(PaMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pa_menu
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    int updateByPrimaryKey(PaMenu record);
}