package cj.netos.uc.plugin.dao;

import cj.netos.uc.domain.TenantAccount;
import cj.netos.uc.domain.TenantAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TenantAccountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_account
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	long countByExample(TenantAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_account
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	int deleteByExample(TenantAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_account
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	int deleteByPrimaryKey(String accountId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_account
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	int insert(TenantAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_account
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	int insertSelective(TenantAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_account
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	List<TenantAccount> selectByExample(TenantAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_account
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	TenantAccount selectByPrimaryKey(String accountId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_account
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	int updateByExampleSelective(@Param("record") TenantAccount record, @Param("example") TenantAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_account
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	int updateByExample(@Param("record") TenantAccount record, @Param("example") TenantAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_account
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	int updateByPrimaryKeySelective(TenantAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_account
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	int updateByPrimaryKey(TenantAccount record);

	void updateAccountEnable(@Param(value = "accountid") String accountid, @Param(value = "enable")boolean enable);

	List<TenantAccount> pageAccount(@Param(value = "tenantid")String tenantid,@Param(value = "currPage") int currPage,@Param(value = "pageSize") int pageSize);

}