package cj.netos.uc.plugin.dao;

import cj.netos.uc.domain.TenantRole;
import cj.netos.uc.domain.TenantRoleExample;

import java.util.List;

import cj.netos.uc.domain.UcUser;
import org.apache.ibatis.annotations.Param;

public interface TenantRoleMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_role
     *
     * @mbg.generated Wed Sep 18 02:11:41 CST 2019
     */
    long countByExample(TenantRoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_role
     *
     * @mbg.generated Wed Sep 18 02:11:41 CST 2019
     */
    int deleteByExample(TenantRoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_role
     *
     * @mbg.generated Wed Sep 18 02:11:41 CST 2019
     */
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_role
     *
     * @mbg.generated Wed Sep 18 02:11:41 CST 2019
     */
    int insert(TenantRole record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_role
     *
     * @mbg.generated Wed Sep 18 02:11:41 CST 2019
     */
    int insertSelective(TenantRole record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_role
     *
     * @mbg.generated Wed Sep 18 02:11:41 CST 2019
     */
    List<TenantRole> selectByExample(TenantRoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_role
     *
     * @mbg.generated Wed Sep 18 02:11:41 CST 2019
     */
    TenantRole selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_role
     *
     * @mbg.generated Wed Sep 18 02:11:41 CST 2019
     */
    int updateByExampleSelective(@Param("record") TenantRole record, @Param("example") TenantRoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_role
     *
     * @mbg.generated Wed Sep 18 02:11:41 CST 2019
     */
    int updateByExample(@Param("record") TenantRole record, @Param("example") TenantRoleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_role
     *
     * @mbg.generated Wed Sep 18 02:11:41 CST 2019
     */
    int updateByPrimaryKeySelective(TenantRole record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_role
     *
     * @mbg.generated Wed Sep 18 02:11:41 CST 2019
     */
    int updateByPrimaryKey(TenantRole record);

    List<TenantRole> pageRole(@Param(value = "tenantid") String tenantid, @Param(value = "currPage") int currPage, @Param(value = "pageSize") int pageSize);

    List<UcUser> pageUserInRole(@Param(value = "roleid") String roleid, @Param(value = "currPage") int currPage, @Param(value = "pageSize") int pageSize);

    List<TenantRole> listRoleOfUser(@Param(value = "uid") String uid);

}