package cj.netos.uc.plugin.dao;

import cj.netos.uc.domain.TenantApp;
import cj.netos.uc.domain.TenantAppExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TenantAppMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_app
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	long countByExample(TenantAppExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_app
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	int deleteByExample(TenantAppExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_app
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	int deleteByPrimaryKey(String appId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_app
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	int insert(TenantApp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_app
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	int insertSelective(TenantApp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_app
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	List<TenantApp> selectByExample(TenantAppExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_app
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	TenantApp selectByPrimaryKey(String appId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_app
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	int updateByExampleSelective(@Param("record") TenantApp record, @Param("example") TenantAppExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_app
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	int updateByExample(@Param("record") TenantApp record, @Param("example") TenantAppExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_app
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	int updateByPrimaryKeySelective(TenantApp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_app
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	int updateByPrimaryKey(TenantApp record);

	List<TenantApp> pageApp(@Param(value = "tenantid") String tenantid, @Param(value = "currPage") int currPage,@Param(value = "pageSize")  int pageSize);
}