package cj.netos.uc.plugin.dao;

import cj.netos.uc.domain.AppRole;
import cj.netos.uc.domain.UaAppRoleUserExample;
import cj.netos.uc.domain.UaAppRoleUserKey;
import java.util.List;

import cj.netos.uc.domain.UcUser;
import org.apache.ibatis.annotations.Param;

public interface UaAppRoleUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ua_app_role_user
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	long countByExample(UaAppRoleUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ua_app_role_user
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	int deleteByExample(UaAppRoleUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ua_app_role_user
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	int deleteByPrimaryKey(UaAppRoleUserKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ua_app_role_user
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	int insert(UaAppRoleUserKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ua_app_role_user
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	int insertSelective(UaAppRoleUserKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ua_app_role_user
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	List<UaAppRoleUserKey> selectByExample(UaAppRoleUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ua_app_role_user
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	int updateByExampleSelective(@Param("record") UaAppRoleUserKey record,
			@Param("example") UaAppRoleUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ua_app_role_user
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	int updateByExample(@Param("record") UaAppRoleUserKey record, @Param("example") UaAppRoleUserExample example);

	List<UcUser> pageUserInRole(@Param(value = "roleid") String roleid, @Param(value = "currPage") int currPage, @Param(value = "pageSize") int pageSize);

	List<AppRole> pageRoleInUser(@Param(value = "uid")String uid, @Param(value = "currPage") int currPage, @Param(value = "pageSize") int pageSize);
}