package cj.netos.uc.plugin.dao;

import cj.netos.uc.domain.UaRoleUserExample;
import cj.netos.uc.domain.UaRoleUserKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UaRoleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ua_role_user
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    long countByExample(UaRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ua_role_user
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    int deleteByExample(UaRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ua_role_user
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    int deleteByPrimaryKey(UaRoleUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ua_role_user
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    int insert(UaRoleUserKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ua_role_user
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    int insertSelective(UaRoleUserKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ua_role_user
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    List<UaRoleUserKey> selectByExample(UaRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ua_role_user
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    int updateByExampleSelective(@Param("record") UaRoleUserKey record, @Param("example") UaRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ua_role_user
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    int updateByExample(@Param("record") UaRoleUserKey record, @Param("example") UaRoleUserExample example);
}