package cj.netos.uc.plugin.dao;

import cj.netos.uc.domain.UcEmployee;
import cj.netos.uc.domain.UcEmployeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UcEmployeeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_empl
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	long countByExample(UcEmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_empl
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	int deleteByExample(UcEmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_empl
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	int deleteByPrimaryKey(String emplId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_empl
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	int insert(UcEmployee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_empl
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	int insertSelective(UcEmployee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_empl
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	List<UcEmployee> selectByExample(UcEmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_empl
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	UcEmployee selectByPrimaryKey(String emplId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_empl
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	int updateByExampleSelective(@Param("record") UcEmployee record, @Param("example") UcEmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_empl
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	int updateByExample(@Param("record") UcEmployee record, @Param("example") UcEmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_empl
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	int updateByPrimaryKeySelective(UcEmployee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_empl
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	int updateByPrimaryKey(UcEmployee record);
}