package cj.netos.uc.plugin.dao;

import cj.netos.uc.domain.UcTenant;
import cj.netos.uc.domain.UcTenantExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UcTenantMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_tenant
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	long countByExample(UcTenantExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_tenant
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	int deleteByExample(UcTenantExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_tenant
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	int deleteByPrimaryKey(String tenantId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_tenant
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	int insert(UcTenant record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_tenant
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	int insertSelective(UcTenant record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_tenant
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	List<UcTenant> selectByExample(UcTenantExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_tenant
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	UcTenant selectByPrimaryKey(String tenantId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_tenant
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	int updateByExampleSelective(@Param("record") UcTenant record, @Param("example") UcTenantExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_tenant
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	int updateByExample(@Param("record") UcTenant record, @Param("example") UcTenantExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_tenant
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	int updateByPrimaryKeySelective(UcTenant record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_tenant
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	int updateByPrimaryKey(UcTenant record);
}