package cj.netos.uc.plugin.dao;

import cj.netos.uc.domain.UcRole;
import cj.netos.uc.domain.UcUser;
import cj.netos.uc.domain.UcUserExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface UcUserMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user
     *
     * @mbg.generated Wed Sep 18 02:11:40 CST 2019
     */
    long countByExample(UcUserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user
     *
     * @mbg.generated Wed Sep 18 02:11:40 CST 2019
     */
    int deleteByExample(UcUserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user
     *
     * @mbg.generated Wed Sep 18 02:11:40 CST 2019
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user
     *
     * @mbg.generated Wed Sep 18 02:11:40 CST 2019
     */
    int insert(UcUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user
     *
     * @mbg.generated Wed Sep 18 02:11:40 CST 2019
     */
    int insertSelective(UcUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user
     *
     * @mbg.generated Wed Sep 18 02:11:40 CST 2019
     */
    List<UcUser> selectByExample(UcUserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user
     *
     * @mbg.generated Wed Sep 18 02:11:40 CST 2019
     */
    UcUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user
     *
     * @mbg.generated Wed Sep 18 02:11:40 CST 2019
     */
    int updateByExampleSelective(@Param("record") UcUser record, @Param("example") UcUserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user
     *
     * @mbg.generated Wed Sep 18 02:11:40 CST 2019
     */
    int updateByExample(@Param("record") UcUser record, @Param("example") UcUserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user
     *
     * @mbg.generated Wed Sep 18 02:11:40 CST 2019
     */
    int updateByPrimaryKeySelective(UcUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user
     *
     * @mbg.generated Wed Sep 18 02:11:40 CST 2019
     */
    int updateByPrimaryKey(UcUser record);

    List<UcUser> pageUser(@Param(value = "currPage") int currPage, @Param(value = "pageSize") int pageSize);


}