package cj.netos.uc.plugin.dao;

import cj.netos.uc.domain.ucUserAttr;
import cj.netos.uc.domain.ucUserAttrExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ucUserAttrMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr
	 * @mbg.generated  Wed Aug 28 22:17:33 PHT 2019
	 */
	long countByExample(ucUserAttrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr
	 * @mbg.generated  Wed Aug 28 22:17:33 PHT 2019
	 */
	int deleteByExample(ucUserAttrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr
	 * @mbg.generated  Wed Aug 28 22:17:33 PHT 2019
	 */
	int deleteByPrimaryKey(String attributeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr
	 * @mbg.generated  Wed Aug 28 22:17:33 PHT 2019
	 */
	int insert(ucUserAttr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr
	 * @mbg.generated  Wed Aug 28 22:17:33 PHT 2019
	 */
	int insertSelective(ucUserAttr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr
	 * @mbg.generated  Wed Aug 28 22:17:33 PHT 2019
	 */
	List<ucUserAttr> selectByExample(ucUserAttrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr
	 * @mbg.generated  Wed Aug 28 22:17:33 PHT 2019
	 */
	ucUserAttr selectByPrimaryKey(String attributeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr
	 * @mbg.generated  Wed Aug 28 22:17:33 PHT 2019
	 */
	int updateByExampleSelective(@Param("record") ucUserAttr record, @Param("example") ucUserAttrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr
	 * @mbg.generated  Wed Aug 28 22:17:33 PHT 2019
	 */
	int updateByExample(@Param("record") ucUserAttr record, @Param("example") ucUserAttrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr
	 * @mbg.generated  Wed Aug 28 22:17:33 PHT 2019
	 */
	int updateByPrimaryKeySelective(ucUserAttr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr
	 * @mbg.generated  Wed Aug 28 22:17:33 PHT 2019
	 */
	int updateByPrimaryKey(ucUserAttr record);
}