package cj.netos.uc.plugin.dao;

import cj.netos.uc.domain.UcUserAttrVal;
import cj.netos.uc.domain.UcUserAttrValExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UcUserAttrValMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr_val
	 * @mbg.generated  Tue Oct 08 11:15:13 CST 2019
	 */
	long countByExample(UcUserAttrValExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr_val
	 * @mbg.generated  Tue Oct 08 11:15:13 CST 2019
	 */
	int deleteByExample(UcUserAttrValExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr_val
	 * @mbg.generated  Tue Oct 08 11:15:13 CST 2019
	 */
	int deleteByPrimaryKey(String valueId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr_val
	 * @mbg.generated  Tue Oct 08 11:15:13 CST 2019
	 */
	int insert(UcUserAttrVal record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr_val
	 * @mbg.generated  Tue Oct 08 11:15:13 CST 2019
	 */
	int insertSelective(UcUserAttrVal record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr_val
	 * @mbg.generated  Tue Oct 08 11:15:13 CST 2019
	 */
	List<UcUserAttrVal> selectByExample(UcUserAttrValExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr_val
	 * @mbg.generated  Tue Oct 08 11:15:13 CST 2019
	 */
	UcUserAttrVal selectByPrimaryKey(String valueId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr_val
	 * @mbg.generated  Tue Oct 08 11:15:13 CST 2019
	 */
	int updateByExampleSelective(@Param("record") UcUserAttrVal record, @Param("example") UcUserAttrValExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr_val
	 * @mbg.generated  Tue Oct 08 11:15:13 CST 2019
	 */
	int updateByExample(@Param("record") UcUserAttrVal record, @Param("example") UcUserAttrValExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr_val
	 * @mbg.generated  Tue Oct 08 11:15:13 CST 2019
	 */
	int updateByPrimaryKeySelective(UcUserAttrVal record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr_val
	 * @mbg.generated  Tue Oct 08 11:15:13 CST 2019
	 */
	int updateByPrimaryKey(UcUserAttrVal record);

	void emptyAttributeValues(@Param(value = "uid") String uid,@Param(value = "segmentid") String segmentid);

	List<UcUserAttrVal> listAttributeValue(@Param(value = "uid")String uid, @Param(value = "segmentid")String segmentid);

}