package cj.netos.uc.domain;

public class AppMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.menu_id
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    private String menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.app_id
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.parent_id
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.menu_name
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.menu_icon
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    private String menuIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.menu_url
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    private String menuUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.order_num
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    private Integer orderNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.menu_id
     *
     * @return the value of app_menu.menu_id
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.menu_id
     *
     * @param menuId the value for app_menu.menu_id
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.app_id
     *
     * @return the value of app_menu.app_id
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.app_id
     *
     * @param appId the value for app_menu.app_id
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.parent_id
     *
     * @return the value of app_menu.parent_id
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.parent_id
     *
     * @param parentId the value for app_menu.parent_id
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.menu_name
     *
     * @return the value of app_menu.menu_name
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.menu_name
     *
     * @param menuName the value for app_menu.menu_name
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.menu_icon
     *
     * @return the value of app_menu.menu_icon
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    public String getMenuIcon() {
        return menuIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.menu_icon
     *
     * @param menuIcon the value for app_menu.menu_icon
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    public void setMenuIcon(String menuIcon) {
        this.menuIcon = menuIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.menu_url
     *
     * @return the value of app_menu.menu_url
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.menu_url
     *
     * @param menuUrl the value for app_menu.menu_url
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.order_num
     *
     * @return the value of app_menu.order_num
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.order_num
     *
     * @param orderNum the value for app_menu.order_num
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }
}