package cj.netos.uc.domain;

import java.util.Date;

public class TenantAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenant_account.account_id
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenant_account.account_name
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenant_account.tenant_id
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenant_account.user_id
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenant_account.account_pwd
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    private String accountPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenant_account.is_enable
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    private Byte isEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenant_account.create_time
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenant_account.open_id
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenant_account.is_plat
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    private String isPlat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenant_account.is_supp
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    private String isSupp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenant_account.is_buy
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    private String isBuy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenant_account.account_tel
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    private String accountTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenant_account.account_email
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    private String accountEmail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenant_account.account_id
     *
     * @return the value of tenant_account.account_id
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenant_account.account_id
     *
     * @param accountId the value for tenant_account.account_id
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenant_account.account_name
     *
     * @return the value of tenant_account.account_name
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenant_account.account_name
     *
     * @param accountName the value for tenant_account.account_name
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenant_account.tenant_id
     *
     * @return the value of tenant_account.tenant_id
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenant_account.tenant_id
     *
     * @param tenantId the value for tenant_account.tenant_id
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenant_account.user_id
     *
     * @return the value of tenant_account.user_id
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenant_account.user_id
     *
     * @param userId the value for tenant_account.user_id
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenant_account.account_pwd
     *
     * @return the value of tenant_account.account_pwd
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public String getAccountPwd() {
        return accountPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenant_account.account_pwd
     *
     * @param accountPwd the value for tenant_account.account_pwd
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public void setAccountPwd(String accountPwd) {
        this.accountPwd = accountPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenant_account.is_enable
     *
     * @return the value of tenant_account.is_enable
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public Byte getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenant_account.is_enable
     *
     * @param isEnable the value for tenant_account.is_enable
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public void setIsEnable(Byte isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenant_account.create_time
     *
     * @return the value of tenant_account.create_time
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenant_account.create_time
     *
     * @param createTime the value for tenant_account.create_time
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenant_account.open_id
     *
     * @return the value of tenant_account.open_id
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenant_account.open_id
     *
     * @param openId the value for tenant_account.open_id
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenant_account.is_plat
     *
     * @return the value of tenant_account.is_plat
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public String getIsPlat() {
        return isPlat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenant_account.is_plat
     *
     * @param isPlat the value for tenant_account.is_plat
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public void setIsPlat(String isPlat) {
        this.isPlat = isPlat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenant_account.is_supp
     *
     * @return the value of tenant_account.is_supp
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public String getIsSupp() {
        return isSupp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenant_account.is_supp
     *
     * @param isSupp the value for tenant_account.is_supp
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public void setIsSupp(String isSupp) {
        this.isSupp = isSupp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenant_account.is_buy
     *
     * @return the value of tenant_account.is_buy
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public String getIsBuy() {
        return isBuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenant_account.is_buy
     *
     * @param isBuy the value for tenant_account.is_buy
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public void setIsBuy(String isBuy) {
        this.isBuy = isBuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenant_account.account_tel
     *
     * @return the value of tenant_account.account_tel
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public String getAccountTel() {
        return accountTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenant_account.account_tel
     *
     * @param accountTel the value for tenant_account.account_tel
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public void setAccountTel(String accountTel) {
        this.accountTel = accountTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenant_account.account_email
     *
     * @return the value of tenant_account.account_email
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public String getAccountEmail() {
        return accountEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenant_account.account_email
     *
     * @param accountEmail the value for tenant_account.account_email
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public void setAccountEmail(String accountEmail) {
        this.accountEmail = accountEmail;
    }
}