package cj.netos.uc.domain;

import java.util.Date;

public class TenantAccount {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenant_account.account_id
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	private String accountId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenant_account.account_name
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	private String accountName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenant_account.name_kind
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	private Byte nameKind;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenant_account.tenant_id
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	private String tenantId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenant_account.user_id
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenant_account.account_pwd
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	private String accountPwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenant_account.is_enable
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	private Byte isEnable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenant_account.create_time
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenant_account.account_id
	 * @return  the value of tenant_account.account_id
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public String getAccountId() {
		return accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenant_account.account_id
	 * @param accountId  the value for tenant_account.account_id
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenant_account.account_name
	 * @return  the value of tenant_account.account_name
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public String getAccountName() {
		return accountName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenant_account.account_name
	 * @param accountName  the value for tenant_account.account_name
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenant_account.name_kind
	 * @return  the value of tenant_account.name_kind
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public Byte getNameKind() {
		return nameKind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenant_account.name_kind
	 * @param nameKind  the value for tenant_account.name_kind
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public void setNameKind(Byte nameKind) {
		this.nameKind = nameKind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenant_account.tenant_id
	 * @return  the value of tenant_account.tenant_id
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public String getTenantId() {
		return tenantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenant_account.tenant_id
	 * @param tenantId  the value for tenant_account.tenant_id
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenant_account.user_id
	 * @return  the value of tenant_account.user_id
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenant_account.user_id
	 * @param userId  the value for tenant_account.user_id
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenant_account.account_pwd
	 * @return  the value of tenant_account.account_pwd
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public String getAccountPwd() {
		return accountPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenant_account.account_pwd
	 * @param accountPwd  the value for tenant_account.account_pwd
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public void setAccountPwd(String accountPwd) {
		this.accountPwd = accountPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenant_account.is_enable
	 * @return  the value of tenant_account.is_enable
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public Byte getIsEnable() {
		return isEnable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenant_account.is_enable
	 * @param isEnable  the value for tenant_account.is_enable
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public void setIsEnable(Byte isEnable) {
		this.isEnable = isEnable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenant_account.create_time
	 * @return  the value of tenant_account.create_time
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenant_account.create_time
	 * @param createTime  the value for tenant_account.create_time
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}