package cj.netos.uc.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TenantAppExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tenant_app
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tenant_app
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tenant_app
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_app
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public TenantAppExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_app
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_app
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_app
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_app
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_app
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_app
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_app
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_app
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_app
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant_app
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tenant_app
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andAppIdIsNull() {
			addCriterion("app_id is null");
			return (Criteria) this;
		}

		public Criteria andAppIdIsNotNull() {
			addCriterion("app_id is not null");
			return (Criteria) this;
		}

		public Criteria andAppIdEqualTo(String value) {
			addCriterion("app_id =", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdNotEqualTo(String value) {
			addCriterion("app_id <>", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdGreaterThan(String value) {
			addCriterion("app_id >", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdGreaterThanOrEqualTo(String value) {
			addCriterion("app_id >=", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdLessThan(String value) {
			addCriterion("app_id <", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdLessThanOrEqualTo(String value) {
			addCriterion("app_id <=", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdLike(String value) {
			addCriterion("app_id like", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdNotLike(String value) {
			addCriterion("app_id not like", value, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdIn(List<String> values) {
			addCriterion("app_id in", values, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdNotIn(List<String> values) {
			addCriterion("app_id not in", values, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdBetween(String value1, String value2) {
			addCriterion("app_id between", value1, value2, "appId");
			return (Criteria) this;
		}

		public Criteria andAppIdNotBetween(String value1, String value2) {
			addCriterion("app_id not between", value1, value2, "appId");
			return (Criteria) this;
		}

		public Criteria andAppNameIsNull() {
			addCriterion("app_name is null");
			return (Criteria) this;
		}

		public Criteria andAppNameIsNotNull() {
			addCriterion("app_name is not null");
			return (Criteria) this;
		}

		public Criteria andAppNameEqualTo(String value) {
			addCriterion("app_name =", value, "appName");
			return (Criteria) this;
		}

		public Criteria andAppNameNotEqualTo(String value) {
			addCriterion("app_name <>", value, "appName");
			return (Criteria) this;
		}

		public Criteria andAppNameGreaterThan(String value) {
			addCriterion("app_name >", value, "appName");
			return (Criteria) this;
		}

		public Criteria andAppNameGreaterThanOrEqualTo(String value) {
			addCriterion("app_name >=", value, "appName");
			return (Criteria) this;
		}

		public Criteria andAppNameLessThan(String value) {
			addCriterion("app_name <", value, "appName");
			return (Criteria) this;
		}

		public Criteria andAppNameLessThanOrEqualTo(String value) {
			addCriterion("app_name <=", value, "appName");
			return (Criteria) this;
		}

		public Criteria andAppNameLike(String value) {
			addCriterion("app_name like", value, "appName");
			return (Criteria) this;
		}

		public Criteria andAppNameNotLike(String value) {
			addCriterion("app_name not like", value, "appName");
			return (Criteria) this;
		}

		public Criteria andAppNameIn(List<String> values) {
			addCriterion("app_name in", values, "appName");
			return (Criteria) this;
		}

		public Criteria andAppNameNotIn(List<String> values) {
			addCriterion("app_name not in", values, "appName");
			return (Criteria) this;
		}

		public Criteria andAppNameBetween(String value1, String value2) {
			addCriterion("app_name between", value1, value2, "appName");
			return (Criteria) this;
		}

		public Criteria andAppNameNotBetween(String value1, String value2) {
			addCriterion("app_name not between", value1, value2, "appName");
			return (Criteria) this;
		}

		public Criteria andTenantIdIsNull() {
			addCriterion("tenant_id is null");
			return (Criteria) this;
		}

		public Criteria andTenantIdIsNotNull() {
			addCriterion("tenant_id is not null");
			return (Criteria) this;
		}

		public Criteria andTenantIdEqualTo(String value) {
			addCriterion("tenant_id =", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdNotEqualTo(String value) {
			addCriterion("tenant_id <>", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdGreaterThan(String value) {
			addCriterion("tenant_id >", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdGreaterThanOrEqualTo(String value) {
			addCriterion("tenant_id >=", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdLessThan(String value) {
			addCriterion("tenant_id <", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdLessThanOrEqualTo(String value) {
			addCriterion("tenant_id <=", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdLike(String value) {
			addCriterion("tenant_id like", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdNotLike(String value) {
			addCriterion("tenant_id not like", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdIn(List<String> values) {
			addCriterion("tenant_id in", values, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdNotIn(List<String> values) {
			addCriterion("tenant_id not in", values, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdBetween(String value1, String value2) {
			addCriterion("tenant_id between", value1, value2, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdNotBetween(String value1, String value2) {
			addCriterion("tenant_id not between", value1, value2, "tenantId");
			return (Criteria) this;
		}

		public Criteria andSecretKeyIsNull() {
			addCriterion("secret_key is null");
			return (Criteria) this;
		}

		public Criteria andSecretKeyIsNotNull() {
			addCriterion("secret_key is not null");
			return (Criteria) this;
		}

		public Criteria andSecretKeyEqualTo(String value) {
			addCriterion("secret_key =", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyNotEqualTo(String value) {
			addCriterion("secret_key <>", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyGreaterThan(String value) {
			addCriterion("secret_key >", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyGreaterThanOrEqualTo(String value) {
			addCriterion("secret_key >=", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyLessThan(String value) {
			addCriterion("secret_key <", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyLessThanOrEqualTo(String value) {
			addCriterion("secret_key <=", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyLike(String value) {
			addCriterion("secret_key like", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyNotLike(String value) {
			addCriterion("secret_key not like", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyIn(List<String> values) {
			addCriterion("secret_key in", values, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyNotIn(List<String> values) {
			addCriterion("secret_key not in", values, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyBetween(String value1, String value2) {
			addCriterion("secret_key between", value1, value2, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyNotBetween(String value1, String value2) {
			addCriterion("secret_key not between", value1, value2, "secretKey");
			return (Criteria) this;
		}

		public Criteria andTokenExpireIsNull() {
			addCriterion("token_expire is null");
			return (Criteria) this;
		}

		public Criteria andTokenExpireIsNotNull() {
			addCriterion("token_expire is not null");
			return (Criteria) this;
		}

		public Criteria andTokenExpireEqualTo(Date value) {
			addCriterion("token_expire =", value, "tokenExpire");
			return (Criteria) this;
		}

		public Criteria andTokenExpireNotEqualTo(Date value) {
			addCriterion("token_expire <>", value, "tokenExpire");
			return (Criteria) this;
		}

		public Criteria andTokenExpireGreaterThan(Date value) {
			addCriterion("token_expire >", value, "tokenExpire");
			return (Criteria) this;
		}

		public Criteria andTokenExpireGreaterThanOrEqualTo(Date value) {
			addCriterion("token_expire >=", value, "tokenExpire");
			return (Criteria) this;
		}

		public Criteria andTokenExpireLessThan(Date value) {
			addCriterion("token_expire <", value, "tokenExpire");
			return (Criteria) this;
		}

		public Criteria andTokenExpireLessThanOrEqualTo(Date value) {
			addCriterion("token_expire <=", value, "tokenExpire");
			return (Criteria) this;
		}

		public Criteria andTokenExpireIn(List<Date> values) {
			addCriterion("token_expire in", values, "tokenExpire");
			return (Criteria) this;
		}

		public Criteria andTokenExpireNotIn(List<Date> values) {
			addCriterion("token_expire not in", values, "tokenExpire");
			return (Criteria) this;
		}

		public Criteria andTokenExpireBetween(Date value1, Date value2) {
			addCriterion("token_expire between", value1, value2, "tokenExpire");
			return (Criteria) this;
		}

		public Criteria andTokenExpireNotBetween(Date value1, Date value2) {
			addCriterion("token_expire not between", value1, value2, "tokenExpire");
			return (Criteria) this;
		}

		public Criteria andAppLogoIsNull() {
			addCriterion("app_logo is null");
			return (Criteria) this;
		}

		public Criteria andAppLogoIsNotNull() {
			addCriterion("app_logo is not null");
			return (Criteria) this;
		}

		public Criteria andAppLogoEqualTo(String value) {
			addCriterion("app_logo =", value, "appLogo");
			return (Criteria) this;
		}

		public Criteria andAppLogoNotEqualTo(String value) {
			addCriterion("app_logo <>", value, "appLogo");
			return (Criteria) this;
		}

		public Criteria andAppLogoGreaterThan(String value) {
			addCriterion("app_logo >", value, "appLogo");
			return (Criteria) this;
		}

		public Criteria andAppLogoGreaterThanOrEqualTo(String value) {
			addCriterion("app_logo >=", value, "appLogo");
			return (Criteria) this;
		}

		public Criteria andAppLogoLessThan(String value) {
			addCriterion("app_logo <", value, "appLogo");
			return (Criteria) this;
		}

		public Criteria andAppLogoLessThanOrEqualTo(String value) {
			addCriterion("app_logo <=", value, "appLogo");
			return (Criteria) this;
		}

		public Criteria andAppLogoLike(String value) {
			addCriterion("app_logo like", value, "appLogo");
			return (Criteria) this;
		}

		public Criteria andAppLogoNotLike(String value) {
			addCriterion("app_logo not like", value, "appLogo");
			return (Criteria) this;
		}

		public Criteria andAppLogoIn(List<String> values) {
			addCriterion("app_logo in", values, "appLogo");
			return (Criteria) this;
		}

		public Criteria andAppLogoNotIn(List<String> values) {
			addCriterion("app_logo not in", values, "appLogo");
			return (Criteria) this;
		}

		public Criteria andAppLogoBetween(String value1, String value2) {
			addCriterion("app_logo between", value1, value2, "appLogo");
			return (Criteria) this;
		}

		public Criteria andAppLogoNotBetween(String value1, String value2) {
			addCriterion("app_logo not between", value1, value2, "appLogo");
			return (Criteria) this;
		}

		public Criteria andCallbackUrlIsNull() {
			addCriterion("callback_url is null");
			return (Criteria) this;
		}

		public Criteria andCallbackUrlIsNotNull() {
			addCriterion("callback_url is not null");
			return (Criteria) this;
		}

		public Criteria andCallbackUrlEqualTo(String value) {
			addCriterion("callback_url =", value, "callbackUrl");
			return (Criteria) this;
		}

		public Criteria andCallbackUrlNotEqualTo(String value) {
			addCriterion("callback_url <>", value, "callbackUrl");
			return (Criteria) this;
		}

		public Criteria andCallbackUrlGreaterThan(String value) {
			addCriterion("callback_url >", value, "callbackUrl");
			return (Criteria) this;
		}

		public Criteria andCallbackUrlGreaterThanOrEqualTo(String value) {
			addCriterion("callback_url >=", value, "callbackUrl");
			return (Criteria) this;
		}

		public Criteria andCallbackUrlLessThan(String value) {
			addCriterion("callback_url <", value, "callbackUrl");
			return (Criteria) this;
		}

		public Criteria andCallbackUrlLessThanOrEqualTo(String value) {
			addCriterion("callback_url <=", value, "callbackUrl");
			return (Criteria) this;
		}

		public Criteria andCallbackUrlLike(String value) {
			addCriterion("callback_url like", value, "callbackUrl");
			return (Criteria) this;
		}

		public Criteria andCallbackUrlNotLike(String value) {
			addCriterion("callback_url not like", value, "callbackUrl");
			return (Criteria) this;
		}

		public Criteria andCallbackUrlIn(List<String> values) {
			addCriterion("callback_url in", values, "callbackUrl");
			return (Criteria) this;
		}

		public Criteria andCallbackUrlNotIn(List<String> values) {
			addCriterion("callback_url not in", values, "callbackUrl");
			return (Criteria) this;
		}

		public Criteria andCallbackUrlBetween(String value1, String value2) {
			addCriterion("callback_url between", value1, value2, "callbackUrl");
			return (Criteria) this;
		}

		public Criteria andCallbackUrlNotBetween(String value1, String value2) {
			addCriterion("callback_url not between", value1, value2, "callbackUrl");
			return (Criteria) this;
		}

		public Criteria andLogoutUrlIsNull() {
			addCriterion("logout_url is null");
			return (Criteria) this;
		}

		public Criteria andLogoutUrlIsNotNull() {
			addCriterion("logout_url is not null");
			return (Criteria) this;
		}

		public Criteria andLogoutUrlEqualTo(String value) {
			addCriterion("logout_url =", value, "logoutUrl");
			return (Criteria) this;
		}

		public Criteria andLogoutUrlNotEqualTo(String value) {
			addCriterion("logout_url <>", value, "logoutUrl");
			return (Criteria) this;
		}

		public Criteria andLogoutUrlGreaterThan(String value) {
			addCriterion("logout_url >", value, "logoutUrl");
			return (Criteria) this;
		}

		public Criteria andLogoutUrlGreaterThanOrEqualTo(String value) {
			addCriterion("logout_url >=", value, "logoutUrl");
			return (Criteria) this;
		}

		public Criteria andLogoutUrlLessThan(String value) {
			addCriterion("logout_url <", value, "logoutUrl");
			return (Criteria) this;
		}

		public Criteria andLogoutUrlLessThanOrEqualTo(String value) {
			addCriterion("logout_url <=", value, "logoutUrl");
			return (Criteria) this;
		}

		public Criteria andLogoutUrlLike(String value) {
			addCriterion("logout_url like", value, "logoutUrl");
			return (Criteria) this;
		}

		public Criteria andLogoutUrlNotLike(String value) {
			addCriterion("logout_url not like", value, "logoutUrl");
			return (Criteria) this;
		}

		public Criteria andLogoutUrlIn(List<String> values) {
			addCriterion("logout_url in", values, "logoutUrl");
			return (Criteria) this;
		}

		public Criteria andLogoutUrlNotIn(List<String> values) {
			addCriterion("logout_url not in", values, "logoutUrl");
			return (Criteria) this;
		}

		public Criteria andLogoutUrlBetween(String value1, String value2) {
			addCriterion("logout_url between", value1, value2, "logoutUrl");
			return (Criteria) this;
		}

		public Criteria andLogoutUrlNotBetween(String value1, String value2) {
			addCriterion("logout_url not between", value1, value2, "logoutUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlIsNull() {
			addCriterion("home_url is null");
			return (Criteria) this;
		}

		public Criteria andHomeUrlIsNotNull() {
			addCriterion("home_url is not null");
			return (Criteria) this;
		}

		public Criteria andHomeUrlEqualTo(String value) {
			addCriterion("home_url =", value, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlNotEqualTo(String value) {
			addCriterion("home_url <>", value, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlGreaterThan(String value) {
			addCriterion("home_url >", value, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlGreaterThanOrEqualTo(String value) {
			addCriterion("home_url >=", value, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlLessThan(String value) {
			addCriterion("home_url <", value, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlLessThanOrEqualTo(String value) {
			addCriterion("home_url <=", value, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlLike(String value) {
			addCriterion("home_url like", value, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlNotLike(String value) {
			addCriterion("home_url not like", value, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlIn(List<String> values) {
			addCriterion("home_url in", values, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlNotIn(List<String> values) {
			addCriterion("home_url not in", values, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlBetween(String value1, String value2) {
			addCriterion("home_url between", value1, value2, "homeUrl");
			return (Criteria) this;
		}

		public Criteria andHomeUrlNotBetween(String value1, String value2) {
			addCriterion("home_url not between", value1, value2, "homeUrl");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tenant_app
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tenant_app
     *
     * @mbg.generated do_not_delete_during_merge Mon Sep 16 16:08:22 PHT 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}