package cj.netos.uc.domain;

public class UaRoleEmployeeKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ua_role_empl.empl_id
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    private String emplId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ua_role_empl.role_id
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ua_role_empl.empl_id
     *
     * @return the value of ua_role_empl.empl_id
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    public String getEmplId() {
        return emplId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ua_role_empl.empl_id
     *
     * @param emplId the value for ua_role_empl.empl_id
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    public void setEmplId(String emplId) {
        this.emplId = emplId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ua_role_empl.role_id
     *
     * @return the value of ua_role_empl.role_id
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ua_role_empl.role_id
     *
     * @param roleId the value for ua_role_empl.role_id
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
}