package cj.netos.uc.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UcCompanyExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table uc_company
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table uc_company
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table uc_company
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_company
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public UcCompanyExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_company
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_company
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_company
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_company
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_company
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_company
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_company
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_company
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_company
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_company
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table uc_company
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCompanyIdIsNull() {
			addCriterion("company_id is null");
			return (Criteria) this;
		}

		public Criteria andCompanyIdIsNotNull() {
			addCriterion("company_id is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyIdEqualTo(String value) {
			addCriterion("company_id =", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdNotEqualTo(String value) {
			addCriterion("company_id <>", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdGreaterThan(String value) {
			addCriterion("company_id >", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdGreaterThanOrEqualTo(String value) {
			addCriterion("company_id >=", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdLessThan(String value) {
			addCriterion("company_id <", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdLessThanOrEqualTo(String value) {
			addCriterion("company_id <=", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdLike(String value) {
			addCriterion("company_id like", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdNotLike(String value) {
			addCriterion("company_id not like", value, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdIn(List<String> values) {
			addCriterion("company_id in", values, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdNotIn(List<String> values) {
			addCriterion("company_id not in", values, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdBetween(String value1, String value2) {
			addCriterion("company_id between", value1, value2, "companyId");
			return (Criteria) this;
		}

		public Criteria andCompanyIdNotBetween(String value1, String value2) {
			addCriterion("company_id not between", value1, value2, "companyId");
			return (Criteria) this;
		}

		public Criteria andParentIdIsNull() {
			addCriterion("parent_id is null");
			return (Criteria) this;
		}

		public Criteria andParentIdIsNotNull() {
			addCriterion("parent_id is not null");
			return (Criteria) this;
		}

		public Criteria andParentIdEqualTo(String value) {
			addCriterion("parent_id =", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdNotEqualTo(String value) {
			addCriterion("parent_id <>", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdGreaterThan(String value) {
			addCriterion("parent_id >", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdGreaterThanOrEqualTo(String value) {
			addCriterion("parent_id >=", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdLessThan(String value) {
			addCriterion("parent_id <", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdLessThanOrEqualTo(String value) {
			addCriterion("parent_id <=", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdLike(String value) {
			addCriterion("parent_id like", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdNotLike(String value) {
			addCriterion("parent_id not like", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdIn(List<String> values) {
			addCriterion("parent_id in", values, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdNotIn(List<String> values) {
			addCriterion("parent_id not in", values, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdBetween(String value1, String value2) {
			addCriterion("parent_id between", value1, value2, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdNotBetween(String value1, String value2) {
			addCriterion("parent_id not between", value1, value2, "parentId");
			return (Criteria) this;
		}

		public Criteria andCompanyNameIsNull() {
			addCriterion("company_name is null");
			return (Criteria) this;
		}

		public Criteria andCompanyNameIsNotNull() {
			addCriterion("company_name is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyNameEqualTo(String value) {
			addCriterion("company_name =", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameNotEqualTo(String value) {
			addCriterion("company_name <>", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameGreaterThan(String value) {
			addCriterion("company_name >", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
			addCriterion("company_name >=", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameLessThan(String value) {
			addCriterion("company_name <", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameLessThanOrEqualTo(String value) {
			addCriterion("company_name <=", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameLike(String value) {
			addCriterion("company_name like", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameNotLike(String value) {
			addCriterion("company_name not like", value, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameIn(List<String> values) {
			addCriterion("company_name in", values, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameNotIn(List<String> values) {
			addCriterion("company_name not in", values, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameBetween(String value1, String value2) {
			addCriterion("company_name between", value1, value2, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyNameNotBetween(String value1, String value2) {
			addCriterion("company_name not between", value1, value2, "companyName");
			return (Criteria) this;
		}

		public Criteria andCompanyCodeIsNull() {
			addCriterion("company_code is null");
			return (Criteria) this;
		}

		public Criteria andCompanyCodeIsNotNull() {
			addCriterion("company_code is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyCodeEqualTo(String value) {
			addCriterion("company_code =", value, "companyCode");
			return (Criteria) this;
		}

		public Criteria andCompanyCodeNotEqualTo(String value) {
			addCriterion("company_code <>", value, "companyCode");
			return (Criteria) this;
		}

		public Criteria andCompanyCodeGreaterThan(String value) {
			addCriterion("company_code >", value, "companyCode");
			return (Criteria) this;
		}

		public Criteria andCompanyCodeGreaterThanOrEqualTo(String value) {
			addCriterion("company_code >=", value, "companyCode");
			return (Criteria) this;
		}

		public Criteria andCompanyCodeLessThan(String value) {
			addCriterion("company_code <", value, "companyCode");
			return (Criteria) this;
		}

		public Criteria andCompanyCodeLessThanOrEqualTo(String value) {
			addCriterion("company_code <=", value, "companyCode");
			return (Criteria) this;
		}

		public Criteria andCompanyCodeLike(String value) {
			addCriterion("company_code like", value, "companyCode");
			return (Criteria) this;
		}

		public Criteria andCompanyCodeNotLike(String value) {
			addCriterion("company_code not like", value, "companyCode");
			return (Criteria) this;
		}

		public Criteria andCompanyCodeIn(List<String> values) {
			addCriterion("company_code in", values, "companyCode");
			return (Criteria) this;
		}

		public Criteria andCompanyCodeNotIn(List<String> values) {
			addCriterion("company_code not in", values, "companyCode");
			return (Criteria) this;
		}

		public Criteria andCompanyCodeBetween(String value1, String value2) {
			addCriterion("company_code between", value1, value2, "companyCode");
			return (Criteria) this;
		}

		public Criteria andCompanyCodeNotBetween(String value1, String value2) {
			addCriterion("company_code not between", value1, value2, "companyCode");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andZipCodeIsNull() {
			addCriterion("zip_code is null");
			return (Criteria) this;
		}

		public Criteria andZipCodeIsNotNull() {
			addCriterion("zip_code is not null");
			return (Criteria) this;
		}

		public Criteria andZipCodeEqualTo(String value) {
			addCriterion("zip_code =", value, "zipCode");
			return (Criteria) this;
		}

		public Criteria andZipCodeNotEqualTo(String value) {
			addCriterion("zip_code <>", value, "zipCode");
			return (Criteria) this;
		}

		public Criteria andZipCodeGreaterThan(String value) {
			addCriterion("zip_code >", value, "zipCode");
			return (Criteria) this;
		}

		public Criteria andZipCodeGreaterThanOrEqualTo(String value) {
			addCriterion("zip_code >=", value, "zipCode");
			return (Criteria) this;
		}

		public Criteria andZipCodeLessThan(String value) {
			addCriterion("zip_code <", value, "zipCode");
			return (Criteria) this;
		}

		public Criteria andZipCodeLessThanOrEqualTo(String value) {
			addCriterion("zip_code <=", value, "zipCode");
			return (Criteria) this;
		}

		public Criteria andZipCodeLike(String value) {
			addCriterion("zip_code like", value, "zipCode");
			return (Criteria) this;
		}

		public Criteria andZipCodeNotLike(String value) {
			addCriterion("zip_code not like", value, "zipCode");
			return (Criteria) this;
		}

		public Criteria andZipCodeIn(List<String> values) {
			addCriterion("zip_code in", values, "zipCode");
			return (Criteria) this;
		}

		public Criteria andZipCodeNotIn(List<String> values) {
			addCriterion("zip_code not in", values, "zipCode");
			return (Criteria) this;
		}

		public Criteria andZipCodeBetween(String value1, String value2) {
			addCriterion("zip_code between", value1, value2, "zipCode");
			return (Criteria) this;
		}

		public Criteria andZipCodeNotBetween(String value1, String value2) {
			addCriterion("zip_code not between", value1, value2, "zipCode");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("address is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("address is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("address =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("address <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("address >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("address >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("address <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("address <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("address like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("address not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("address in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("address not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("address between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("address not between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andWebsiteIsNull() {
			addCriterion("website is null");
			return (Criteria) this;
		}

		public Criteria andWebsiteIsNotNull() {
			addCriterion("website is not null");
			return (Criteria) this;
		}

		public Criteria andWebsiteEqualTo(String value) {
			addCriterion("website =", value, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteNotEqualTo(String value) {
			addCriterion("website <>", value, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteGreaterThan(String value) {
			addCriterion("website >", value, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteGreaterThanOrEqualTo(String value) {
			addCriterion("website >=", value, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteLessThan(String value) {
			addCriterion("website <", value, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteLessThanOrEqualTo(String value) {
			addCriterion("website <=", value, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteLike(String value) {
			addCriterion("website like", value, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteNotLike(String value) {
			addCriterion("website not like", value, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteIn(List<String> values) {
			addCriterion("website in", values, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteNotIn(List<String> values) {
			addCriterion("website not in", values, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteBetween(String value1, String value2) {
			addCriterion("website between", value1, value2, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteNotBetween(String value1, String value2) {
			addCriterion("website not between", value1, value2, "website");
			return (Criteria) this;
		}

		public Criteria andFexIsNull() {
			addCriterion("fex is null");
			return (Criteria) this;
		}

		public Criteria andFexIsNotNull() {
			addCriterion("fex is not null");
			return (Criteria) this;
		}

		public Criteria andFexEqualTo(String value) {
			addCriterion("fex =", value, "fex");
			return (Criteria) this;
		}

		public Criteria andFexNotEqualTo(String value) {
			addCriterion("fex <>", value, "fex");
			return (Criteria) this;
		}

		public Criteria andFexGreaterThan(String value) {
			addCriterion("fex >", value, "fex");
			return (Criteria) this;
		}

		public Criteria andFexGreaterThanOrEqualTo(String value) {
			addCriterion("fex >=", value, "fex");
			return (Criteria) this;
		}

		public Criteria andFexLessThan(String value) {
			addCriterion("fex <", value, "fex");
			return (Criteria) this;
		}

		public Criteria andFexLessThanOrEqualTo(String value) {
			addCriterion("fex <=", value, "fex");
			return (Criteria) this;
		}

		public Criteria andFexLike(String value) {
			addCriterion("fex like", value, "fex");
			return (Criteria) this;
		}

		public Criteria andFexNotLike(String value) {
			addCriterion("fex not like", value, "fex");
			return (Criteria) this;
		}

		public Criteria andFexIn(List<String> values) {
			addCriterion("fex in", values, "fex");
			return (Criteria) this;
		}

		public Criteria andFexNotIn(List<String> values) {
			addCriterion("fex not in", values, "fex");
			return (Criteria) this;
		}

		public Criteria andFexBetween(String value1, String value2) {
			addCriterion("fex between", value1, value2, "fex");
			return (Criteria) this;
		}

		public Criteria andFexNotBetween(String value1, String value2) {
			addCriterion("fex not between", value1, value2, "fex");
			return (Criteria) this;
		}

		public Criteria andTelIsNull() {
			addCriterion("tel is null");
			return (Criteria) this;
		}

		public Criteria andTelIsNotNull() {
			addCriterion("tel is not null");
			return (Criteria) this;
		}

		public Criteria andTelEqualTo(String value) {
			addCriterion("tel =", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotEqualTo(String value) {
			addCriterion("tel <>", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelGreaterThan(String value) {
			addCriterion("tel >", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelGreaterThanOrEqualTo(String value) {
			addCriterion("tel >=", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelLessThan(String value) {
			addCriterion("tel <", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelLessThanOrEqualTo(String value) {
			addCriterion("tel <=", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelLike(String value) {
			addCriterion("tel like", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotLike(String value) {
			addCriterion("tel not like", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelIn(List<String> values) {
			addCriterion("tel in", values, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotIn(List<String> values) {
			addCriterion("tel not in", values, "tel");
			return (Criteria) this;
		}

		public Criteria andTelBetween(String value1, String value2) {
			addCriterion("tel between", value1, value2, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotBetween(String value1, String value2) {
			addCriterion("tel not between", value1, value2, "tel");
			return (Criteria) this;
		}

		public Criteria andBankIsNull() {
			addCriterion("bank is null");
			return (Criteria) this;
		}

		public Criteria andBankIsNotNull() {
			addCriterion("bank is not null");
			return (Criteria) this;
		}

		public Criteria andBankEqualTo(String value) {
			addCriterion("bank =", value, "bank");
			return (Criteria) this;
		}

		public Criteria andBankNotEqualTo(String value) {
			addCriterion("bank <>", value, "bank");
			return (Criteria) this;
		}

		public Criteria andBankGreaterThan(String value) {
			addCriterion("bank >", value, "bank");
			return (Criteria) this;
		}

		public Criteria andBankGreaterThanOrEqualTo(String value) {
			addCriterion("bank >=", value, "bank");
			return (Criteria) this;
		}

		public Criteria andBankLessThan(String value) {
			addCriterion("bank <", value, "bank");
			return (Criteria) this;
		}

		public Criteria andBankLessThanOrEqualTo(String value) {
			addCriterion("bank <=", value, "bank");
			return (Criteria) this;
		}

		public Criteria andBankLike(String value) {
			addCriterion("bank like", value, "bank");
			return (Criteria) this;
		}

		public Criteria andBankNotLike(String value) {
			addCriterion("bank not like", value, "bank");
			return (Criteria) this;
		}

		public Criteria andBankIn(List<String> values) {
			addCriterion("bank in", values, "bank");
			return (Criteria) this;
		}

		public Criteria andBankNotIn(List<String> values) {
			addCriterion("bank not in", values, "bank");
			return (Criteria) this;
		}

		public Criteria andBankBetween(String value1, String value2) {
			addCriterion("bank between", value1, value2, "bank");
			return (Criteria) this;
		}

		public Criteria andBankNotBetween(String value1, String value2) {
			addCriterion("bank not between", value1, value2, "bank");
			return (Criteria) this;
		}

		public Criteria andBankAccountIsNull() {
			addCriterion("bank_account is null");
			return (Criteria) this;
		}

		public Criteria andBankAccountIsNotNull() {
			addCriterion("bank_account is not null");
			return (Criteria) this;
		}

		public Criteria andBankAccountEqualTo(String value) {
			addCriterion("bank_account =", value, "bankAccount");
			return (Criteria) this;
		}

		public Criteria andBankAccountNotEqualTo(String value) {
			addCriterion("bank_account <>", value, "bankAccount");
			return (Criteria) this;
		}

		public Criteria andBankAccountGreaterThan(String value) {
			addCriterion("bank_account >", value, "bankAccount");
			return (Criteria) this;
		}

		public Criteria andBankAccountGreaterThanOrEqualTo(String value) {
			addCriterion("bank_account >=", value, "bankAccount");
			return (Criteria) this;
		}

		public Criteria andBankAccountLessThan(String value) {
			addCriterion("bank_account <", value, "bankAccount");
			return (Criteria) this;
		}

		public Criteria andBankAccountLessThanOrEqualTo(String value) {
			addCriterion("bank_account <=", value, "bankAccount");
			return (Criteria) this;
		}

		public Criteria andBankAccountLike(String value) {
			addCriterion("bank_account like", value, "bankAccount");
			return (Criteria) this;
		}

		public Criteria andBankAccountNotLike(String value) {
			addCriterion("bank_account not like", value, "bankAccount");
			return (Criteria) this;
		}

		public Criteria andBankAccountIn(List<String> values) {
			addCriterion("bank_account in", values, "bankAccount");
			return (Criteria) this;
		}

		public Criteria andBankAccountNotIn(List<String> values) {
			addCriterion("bank_account not in", values, "bankAccount");
			return (Criteria) this;
		}

		public Criteria andBankAccountBetween(String value1, String value2) {
			addCriterion("bank_account between", value1, value2, "bankAccount");
			return (Criteria) this;
		}

		public Criteria andBankAccountNotBetween(String value1, String value2) {
			addCriterion("bank_account not between", value1, value2, "bankAccount");
			return (Criteria) this;
		}

		public Criteria andLegalNameIsNull() {
			addCriterion("legal_name is null");
			return (Criteria) this;
		}

		public Criteria andLegalNameIsNotNull() {
			addCriterion("legal_name is not null");
			return (Criteria) this;
		}

		public Criteria andLegalNameEqualTo(String value) {
			addCriterion("legal_name =", value, "legalName");
			return (Criteria) this;
		}

		public Criteria andLegalNameNotEqualTo(String value) {
			addCriterion("legal_name <>", value, "legalName");
			return (Criteria) this;
		}

		public Criteria andLegalNameGreaterThan(String value) {
			addCriterion("legal_name >", value, "legalName");
			return (Criteria) this;
		}

		public Criteria andLegalNameGreaterThanOrEqualTo(String value) {
			addCriterion("legal_name >=", value, "legalName");
			return (Criteria) this;
		}

		public Criteria andLegalNameLessThan(String value) {
			addCriterion("legal_name <", value, "legalName");
			return (Criteria) this;
		}

		public Criteria andLegalNameLessThanOrEqualTo(String value) {
			addCriterion("legal_name <=", value, "legalName");
			return (Criteria) this;
		}

		public Criteria andLegalNameLike(String value) {
			addCriterion("legal_name like", value, "legalName");
			return (Criteria) this;
		}

		public Criteria andLegalNameNotLike(String value) {
			addCriterion("legal_name not like", value, "legalName");
			return (Criteria) this;
		}

		public Criteria andLegalNameIn(List<String> values) {
			addCriterion("legal_name in", values, "legalName");
			return (Criteria) this;
		}

		public Criteria andLegalNameNotIn(List<String> values) {
			addCriterion("legal_name not in", values, "legalName");
			return (Criteria) this;
		}

		public Criteria andLegalNameBetween(String value1, String value2) {
			addCriterion("legal_name between", value1, value2, "legalName");
			return (Criteria) this;
		}

		public Criteria andLegalNameNotBetween(String value1, String value2) {
			addCriterion("legal_name not between", value1, value2, "legalName");
			return (Criteria) this;
		}

		public Criteria andLegalTelIsNull() {
			addCriterion("legal_tel is null");
			return (Criteria) this;
		}

		public Criteria andLegalTelIsNotNull() {
			addCriterion("legal_tel is not null");
			return (Criteria) this;
		}

		public Criteria andLegalTelEqualTo(String value) {
			addCriterion("legal_tel =", value, "legalTel");
			return (Criteria) this;
		}

		public Criteria andLegalTelNotEqualTo(String value) {
			addCriterion("legal_tel <>", value, "legalTel");
			return (Criteria) this;
		}

		public Criteria andLegalTelGreaterThan(String value) {
			addCriterion("legal_tel >", value, "legalTel");
			return (Criteria) this;
		}

		public Criteria andLegalTelGreaterThanOrEqualTo(String value) {
			addCriterion("legal_tel >=", value, "legalTel");
			return (Criteria) this;
		}

		public Criteria andLegalTelLessThan(String value) {
			addCriterion("legal_tel <", value, "legalTel");
			return (Criteria) this;
		}

		public Criteria andLegalTelLessThanOrEqualTo(String value) {
			addCriterion("legal_tel <=", value, "legalTel");
			return (Criteria) this;
		}

		public Criteria andLegalTelLike(String value) {
			addCriterion("legal_tel like", value, "legalTel");
			return (Criteria) this;
		}

		public Criteria andLegalTelNotLike(String value) {
			addCriterion("legal_tel not like", value, "legalTel");
			return (Criteria) this;
		}

		public Criteria andLegalTelIn(List<String> values) {
			addCriterion("legal_tel in", values, "legalTel");
			return (Criteria) this;
		}

		public Criteria andLegalTelNotIn(List<String> values) {
			addCriterion("legal_tel not in", values, "legalTel");
			return (Criteria) this;
		}

		public Criteria andLegalTelBetween(String value1, String value2) {
			addCriterion("legal_tel between", value1, value2, "legalTel");
			return (Criteria) this;
		}

		public Criteria andLegalTelNotBetween(String value1, String value2) {
			addCriterion("legal_tel not between", value1, value2, "legalTel");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table uc_company
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table uc_company
     *
     * @mbg.generated do_not_delete_during_merge Mon Sep 16 16:08:22 PHT 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}