package cj.netos.uc.domain;

import java.util.Date;

public class UcCompany {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_company.company_id
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	private String companyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_company.parent_id
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	private String parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_company.company_name
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	private String companyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_company.company_code
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	private String companyCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_company.create_time
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_company.zip_code
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	private String zipCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_company.address
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_company.email
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_company.website
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	private String website;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_company.fex
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	private String fex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_company.tel
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	private String tel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_company.bank
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	private String bank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_company.bank_account
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	private String bankAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_company.legal_name
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	private String legalName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_company.legal_tel
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	private String legalTel;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_company.company_id
	 * @return  the value of uc_company.company_id
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	public String getCompanyId() {
		return companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_company.company_id
	 * @param companyId  the value for uc_company.company_id
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_company.parent_id
	 * @return  the value of uc_company.parent_id
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	public String getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_company.parent_id
	 * @param parentId  the value for uc_company.parent_id
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_company.company_name
	 * @return  the value of uc_company.company_name
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	public String getCompanyName() {
		return companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_company.company_name
	 * @param companyName  the value for uc_company.company_name
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_company.company_code
	 * @return  the value of uc_company.company_code
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	public String getCompanyCode() {
		return companyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_company.company_code
	 * @param companyCode  the value for uc_company.company_code
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_company.create_time
	 * @return  the value of uc_company.create_time
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_company.create_time
	 * @param createTime  the value for uc_company.create_time
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_company.zip_code
	 * @return  the value of uc_company.zip_code
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	public String getZipCode() {
		return zipCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_company.zip_code
	 * @param zipCode  the value for uc_company.zip_code
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_company.address
	 * @return  the value of uc_company.address
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_company.address
	 * @param address  the value for uc_company.address
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_company.email
	 * @return  the value of uc_company.email
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_company.email
	 * @param email  the value for uc_company.email
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_company.website
	 * @return  the value of uc_company.website
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	public String getWebsite() {
		return website;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_company.website
	 * @param website  the value for uc_company.website
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	public void setWebsite(String website) {
		this.website = website;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_company.fex
	 * @return  the value of uc_company.fex
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	public String getFex() {
		return fex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_company.fex
	 * @param fex  the value for uc_company.fex
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	public void setFex(String fex) {
		this.fex = fex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_company.tel
	 * @return  the value of uc_company.tel
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_company.tel
	 * @param tel  the value for uc_company.tel
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_company.bank
	 * @return  the value of uc_company.bank
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	public String getBank() {
		return bank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_company.bank
	 * @param bank  the value for uc_company.bank
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	public void setBank(String bank) {
		this.bank = bank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_company.bank_account
	 * @return  the value of uc_company.bank_account
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	public String getBankAccount() {
		return bankAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_company.bank_account
	 * @param bankAccount  the value for uc_company.bank_account
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	public void setBankAccount(String bankAccount) {
		this.bankAccount = bankAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_company.legal_name
	 * @return  the value of uc_company.legal_name
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	public String getLegalName() {
		return legalName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_company.legal_name
	 * @param legalName  the value for uc_company.legal_name
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	public void setLegalName(String legalName) {
		this.legalName = legalName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_company.legal_tel
	 * @return  the value of uc_company.legal_tel
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	public String getLegalTel() {
		return legalTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_company.legal_tel
	 * @param legalTel  the value for uc_company.legal_tel
	 * @mbg.generated  Wed Sep 18 02:11:41 CST 2019
	 */
	public void setLegalTel(String legalTel) {
		this.legalTel = legalTel;
	}
}