package cj.netos.uc.domain;

import java.util.Date;

public class UcDept {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_dept.dept_id
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	private String deptId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_dept.parent_id
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	private String parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_dept.company_id
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	private String companyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_dept.dept_name
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	private String deptName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_dept.create_time
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_dept.dept_code
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	private String deptCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_dept.tel
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	private String tel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_dept.fax
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	private String fax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_dept.zip_code
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	private String zipCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_dept.address
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	private String address;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_dept.dept_id
	 * @return  the value of uc_dept.dept_id
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	public String getDeptId() {
		return deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_dept.dept_id
	 * @param deptId  the value for uc_dept.dept_id
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_dept.parent_id
	 * @return  the value of uc_dept.parent_id
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	public String getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_dept.parent_id
	 * @param parentId  the value for uc_dept.parent_id
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_dept.company_id
	 * @return  the value of uc_dept.company_id
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	public String getCompanyId() {
		return companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_dept.company_id
	 * @param companyId  the value for uc_dept.company_id
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_dept.dept_name
	 * @return  the value of uc_dept.dept_name
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	public String getDeptName() {
		return deptName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_dept.dept_name
	 * @param deptName  the value for uc_dept.dept_name
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_dept.create_time
	 * @return  the value of uc_dept.create_time
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_dept.create_time
	 * @param createTime  the value for uc_dept.create_time
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_dept.dept_code
	 * @return  the value of uc_dept.dept_code
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	public String getDeptCode() {
		return deptCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_dept.dept_code
	 * @param deptCode  the value for uc_dept.dept_code
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	public void setDeptCode(String deptCode) {
		this.deptCode = deptCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_dept.tel
	 * @return  the value of uc_dept.tel
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_dept.tel
	 * @param tel  the value for uc_dept.tel
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_dept.fax
	 * @return  the value of uc_dept.fax
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	public String getFax() {
		return fax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_dept.fax
	 * @param fax  the value for uc_dept.fax
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	public void setFax(String fax) {
		this.fax = fax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_dept.zip_code
	 * @return  the value of uc_dept.zip_code
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	public String getZipCode() {
		return zipCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_dept.zip_code
	 * @param zipCode  the value for uc_dept.zip_code
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_dept.address
	 * @return  the value of uc_dept.address
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_dept.address
	 * @param address  the value for uc_dept.address
	 * @mbg.generated  Tue Oct 08 11:15:14 CST 2019
	 */
	public void setAddress(String address) {
		this.address = address;
	}
}