package cj.netos.uc.domain;

import java.util.Date;

public class UcEmployee {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_empl.empl_id
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	private String emplId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_empl.user_id
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_empl.company_id
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	private String companyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_empl.dept_id
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	private String deptId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_empl.create_time
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_empl.empl_code
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	private String emplCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_empl.empl_position
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	private String emplPosition;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_empl.entry_time
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	private Date entryTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_empl.empl_id
	 * @return  the value of uc_empl.empl_id
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public String getEmplId() {
		return emplId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_empl.empl_id
	 * @param emplId  the value for uc_empl.empl_id
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public void setEmplId(String emplId) {
		this.emplId = emplId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_empl.user_id
	 * @return  the value of uc_empl.user_id
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_empl.user_id
	 * @param userId  the value for uc_empl.user_id
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_empl.company_id
	 * @return  the value of uc_empl.company_id
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public String getCompanyId() {
		return companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_empl.company_id
	 * @param companyId  the value for uc_empl.company_id
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_empl.dept_id
	 * @return  the value of uc_empl.dept_id
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public String getDeptId() {
		return deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_empl.dept_id
	 * @param deptId  the value for uc_empl.dept_id
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_empl.create_time
	 * @return  the value of uc_empl.create_time
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_empl.create_time
	 * @param createTime  the value for uc_empl.create_time
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_empl.empl_code
	 * @return  the value of uc_empl.empl_code
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public String getEmplCode() {
		return emplCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_empl.empl_code
	 * @param emplCode  the value for uc_empl.empl_code
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public void setEmplCode(String emplCode) {
		this.emplCode = emplCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_empl.empl_position
	 * @return  the value of uc_empl.empl_position
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public String getEmplPosition() {
		return emplPosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_empl.empl_position
	 * @param emplPosition  the value for uc_empl.empl_position
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public void setEmplPosition(String emplPosition) {
		this.emplPosition = emplPosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_empl.entry_time
	 * @return  the value of uc_empl.entry_time
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public Date getEntryTime() {
		return entryTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_empl.entry_time
	 * @param entryTime  the value for uc_empl.entry_time
	 * @mbg.generated  Tue Sep 17 12:57:10 PHT 2019
	 */
	public void setEntryTime(Date entryTime) {
		this.entryTime = entryTime;
	}
}