package cj.netos.uc.domain;

public class UcRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_role.role_id
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_role.role_name
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    private String roleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_role.role_id
     *
     * @return the value of uc_role.role_id
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_role.role_id
     *
     * @param roleId the value for uc_role.role_id
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_role.role_name
     *
     * @return the value of uc_role.role_name
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_role.role_name
     *
     * @param roleName the value for uc_role.role_name
     *
     * @mbg.generated Wed Aug 28 22:17:33 PHT 2019
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
}