package cj.netos.uc.domain;

public class UcRole {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_role.role_id
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	private String roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_role.role_name
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	private String roleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_role.is_Inheritable
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	private Boolean isInheritable;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_role.role_id
	 * @return  the value of uc_role.role_id
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public String getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_role.role_id
	 * @param roleId  the value for uc_role.role_id
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_role.role_name
	 * @return  the value of uc_role.role_name
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_role.role_name
	 * @param roleName  the value for uc_role.role_name
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_role.is_Inheritable
	 * @return  the value of uc_role.is_Inheritable
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public Boolean getIsInheritable() {
		return isInheritable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_role.is_Inheritable
	 * @param isInheritable  the value for uc_role.is_Inheritable
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public void setIsInheritable(Boolean isInheritable) {
		this.isInheritable = isInheritable;
	}
}