package cj.netos.uc.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UcTenantExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table uc_tenant
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table uc_tenant
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table uc_tenant
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_tenant
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public UcTenantExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_tenant
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_tenant
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_tenant
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_tenant
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_tenant
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_tenant
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_tenant
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_tenant
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_tenant
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_tenant
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table uc_tenant
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andTenantIdIsNull() {
			addCriterion("tenant_id is null");
			return (Criteria) this;
		}

		public Criteria andTenantIdIsNotNull() {
			addCriterion("tenant_id is not null");
			return (Criteria) this;
		}

		public Criteria andTenantIdEqualTo(String value) {
			addCriterion("tenant_id =", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdNotEqualTo(String value) {
			addCriterion("tenant_id <>", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdGreaterThan(String value) {
			addCriterion("tenant_id >", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdGreaterThanOrEqualTo(String value) {
			addCriterion("tenant_id >=", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdLessThan(String value) {
			addCriterion("tenant_id <", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdLessThanOrEqualTo(String value) {
			addCriterion("tenant_id <=", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdLike(String value) {
			addCriterion("tenant_id like", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdNotLike(String value) {
			addCriterion("tenant_id not like", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdIn(List<String> values) {
			addCriterion("tenant_id in", values, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdNotIn(List<String> values) {
			addCriterion("tenant_id not in", values, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdBetween(String value1, String value2) {
			addCriterion("tenant_id between", value1, value2, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdNotBetween(String value1, String value2) {
			addCriterion("tenant_id not between", value1, value2, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantNameIsNull() {
			addCriterion("tenant_name is null");
			return (Criteria) this;
		}

		public Criteria andTenantNameIsNotNull() {
			addCriterion("tenant_name is not null");
			return (Criteria) this;
		}

		public Criteria andTenantNameEqualTo(String value) {
			addCriterion("tenant_name =", value, "tenantName");
			return (Criteria) this;
		}

		public Criteria andTenantNameNotEqualTo(String value) {
			addCriterion("tenant_name <>", value, "tenantName");
			return (Criteria) this;
		}

		public Criteria andTenantNameGreaterThan(String value) {
			addCriterion("tenant_name >", value, "tenantName");
			return (Criteria) this;
		}

		public Criteria andTenantNameGreaterThanOrEqualTo(String value) {
			addCriterion("tenant_name >=", value, "tenantName");
			return (Criteria) this;
		}

		public Criteria andTenantNameLessThan(String value) {
			addCriterion("tenant_name <", value, "tenantName");
			return (Criteria) this;
		}

		public Criteria andTenantNameLessThanOrEqualTo(String value) {
			addCriterion("tenant_name <=", value, "tenantName");
			return (Criteria) this;
		}

		public Criteria andTenantNameLike(String value) {
			addCriterion("tenant_name like", value, "tenantName");
			return (Criteria) this;
		}

		public Criteria andTenantNameNotLike(String value) {
			addCriterion("tenant_name not like", value, "tenantName");
			return (Criteria) this;
		}

		public Criteria andTenantNameIn(List<String> values) {
			addCriterion("tenant_name in", values, "tenantName");
			return (Criteria) this;
		}

		public Criteria andTenantNameNotIn(List<String> values) {
			addCriterion("tenant_name not in", values, "tenantName");
			return (Criteria) this;
		}

		public Criteria andTenantNameBetween(String value1, String value2) {
			addCriterion("tenant_name between", value1, value2, "tenantName");
			return (Criteria) this;
		}

		public Criteria andTenantNameNotBetween(String value1, String value2) {
			addCriterion("tenant_name not between", value1, value2, "tenantName");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("user_id like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("user_id not like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<String> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<String> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andIsEnableIsNull() {
			addCriterion("is_enable is null");
			return (Criteria) this;
		}

		public Criteria andIsEnableIsNotNull() {
			addCriterion("is_enable is not null");
			return (Criteria) this;
		}

		public Criteria andIsEnableEqualTo(Byte value) {
			addCriterion("is_enable =", value, "isEnable");
			return (Criteria) this;
		}

		public Criteria andIsEnableNotEqualTo(Byte value) {
			addCriterion("is_enable <>", value, "isEnable");
			return (Criteria) this;
		}

		public Criteria andIsEnableGreaterThan(Byte value) {
			addCriterion("is_enable >", value, "isEnable");
			return (Criteria) this;
		}

		public Criteria andIsEnableGreaterThanOrEqualTo(Byte value) {
			addCriterion("is_enable >=", value, "isEnable");
			return (Criteria) this;
		}

		public Criteria andIsEnableLessThan(Byte value) {
			addCriterion("is_enable <", value, "isEnable");
			return (Criteria) this;
		}

		public Criteria andIsEnableLessThanOrEqualTo(Byte value) {
			addCriterion("is_enable <=", value, "isEnable");
			return (Criteria) this;
		}

		public Criteria andIsEnableIn(List<Byte> values) {
			addCriterion("is_enable in", values, "isEnable");
			return (Criteria) this;
		}

		public Criteria andIsEnableNotIn(List<Byte> values) {
			addCriterion("is_enable not in", values, "isEnable");
			return (Criteria) this;
		}

		public Criteria andIsEnableBetween(Byte value1, Byte value2) {
			addCriterion("is_enable between", value1, value2, "isEnable");
			return (Criteria) this;
		}

		public Criteria andIsEnableNotBetween(Byte value1, Byte value2) {
			addCriterion("is_enable not between", value1, value2, "isEnable");
			return (Criteria) this;
		}

		public Criteria andSecretKeyIsNull() {
			addCriterion("secret_key is null");
			return (Criteria) this;
		}

		public Criteria andSecretKeyIsNotNull() {
			addCriterion("secret_key is not null");
			return (Criteria) this;
		}

		public Criteria andSecretKeyEqualTo(String value) {
			addCriterion("secret_key =", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyNotEqualTo(String value) {
			addCriterion("secret_key <>", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyGreaterThan(String value) {
			addCriterion("secret_key >", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyGreaterThanOrEqualTo(String value) {
			addCriterion("secret_key >=", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyLessThan(String value) {
			addCriterion("secret_key <", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyLessThanOrEqualTo(String value) {
			addCriterion("secret_key <=", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyLike(String value) {
			addCriterion("secret_key like", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyNotLike(String value) {
			addCriterion("secret_key not like", value, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyIn(List<String> values) {
			addCriterion("secret_key in", values, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyNotIn(List<String> values) {
			addCriterion("secret_key not in", values, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyBetween(String value1, String value2) {
			addCriterion("secret_key between", value1, value2, "secretKey");
			return (Criteria) this;
		}

		public Criteria andSecretKeyNotBetween(String value1, String value2) {
			addCriterion("secret_key not between", value1, value2, "secretKey");
			return (Criteria) this;
		}

		public Criteria andWebsiteIsNull() {
			addCriterion("website is null");
			return (Criteria) this;
		}

		public Criteria andWebsiteIsNotNull() {
			addCriterion("website is not null");
			return (Criteria) this;
		}

		public Criteria andWebsiteEqualTo(String value) {
			addCriterion("website =", value, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteNotEqualTo(String value) {
			addCriterion("website <>", value, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteGreaterThan(String value) {
			addCriterion("website >", value, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteGreaterThanOrEqualTo(String value) {
			addCriterion("website >=", value, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteLessThan(String value) {
			addCriterion("website <", value, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteLessThanOrEqualTo(String value) {
			addCriterion("website <=", value, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteLike(String value) {
			addCriterion("website like", value, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteNotLike(String value) {
			addCriterion("website not like", value, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteIn(List<String> values) {
			addCriterion("website in", values, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteNotIn(List<String> values) {
			addCriterion("website not in", values, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteBetween(String value1, String value2) {
			addCriterion("website between", value1, value2, "website");
			return (Criteria) this;
		}

		public Criteria andWebsiteNotBetween(String value1, String value2) {
			addCriterion("website not between", value1, value2, "website");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table uc_tenant
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table uc_tenant
     *
     * @mbg.generated do_not_delete_during_merge Mon Sep 16 16:08:22 PHT 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}