package cj.netos.uc.domain;

import java.util.ArrayList;
import java.util.List;

public class UcUserAttrValExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table uc_user_attr_val
	 * @mbg.generated  Wed Sep 18 02:11:40 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table uc_user_attr_val
	 * @mbg.generated  Wed Sep 18 02:11:40 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table uc_user_attr_val
	 * @mbg.generated  Wed Sep 18 02:11:40 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr_val
	 * @mbg.generated  Wed Sep 18 02:11:40 CST 2019
	 */
	public UcUserAttrValExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr_val
	 * @mbg.generated  Wed Sep 18 02:11:40 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr_val
	 * @mbg.generated  Wed Sep 18 02:11:40 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr_val
	 * @mbg.generated  Wed Sep 18 02:11:40 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr_val
	 * @mbg.generated  Wed Sep 18 02:11:40 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr_val
	 * @mbg.generated  Wed Sep 18 02:11:40 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr_val
	 * @mbg.generated  Wed Sep 18 02:11:40 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr_val
	 * @mbg.generated  Wed Sep 18 02:11:40 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr_val
	 * @mbg.generated  Wed Sep 18 02:11:40 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr_val
	 * @mbg.generated  Wed Sep 18 02:11:40 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_user_attr_val
	 * @mbg.generated  Wed Sep 18 02:11:40 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table uc_user_attr_val
	 * @mbg.generated  Wed Sep 18 02:11:40 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andValueIdIsNull() {
			addCriterion("value_id is null");
			return (Criteria) this;
		}

		public Criteria andValueIdIsNotNull() {
			addCriterion("value_id is not null");
			return (Criteria) this;
		}

		public Criteria andValueIdEqualTo(String value) {
			addCriterion("value_id =", value, "valueId");
			return (Criteria) this;
		}

		public Criteria andValueIdNotEqualTo(String value) {
			addCriterion("value_id <>", value, "valueId");
			return (Criteria) this;
		}

		public Criteria andValueIdGreaterThan(String value) {
			addCriterion("value_id >", value, "valueId");
			return (Criteria) this;
		}

		public Criteria andValueIdGreaterThanOrEqualTo(String value) {
			addCriterion("value_id >=", value, "valueId");
			return (Criteria) this;
		}

		public Criteria andValueIdLessThan(String value) {
			addCriterion("value_id <", value, "valueId");
			return (Criteria) this;
		}

		public Criteria andValueIdLessThanOrEqualTo(String value) {
			addCriterion("value_id <=", value, "valueId");
			return (Criteria) this;
		}

		public Criteria andValueIdLike(String value) {
			addCriterion("value_id like", value, "valueId");
			return (Criteria) this;
		}

		public Criteria andValueIdNotLike(String value) {
			addCriterion("value_id not like", value, "valueId");
			return (Criteria) this;
		}

		public Criteria andValueIdIn(List<String> values) {
			addCriterion("value_id in", values, "valueId");
			return (Criteria) this;
		}

		public Criteria andValueIdNotIn(List<String> values) {
			addCriterion("value_id not in", values, "valueId");
			return (Criteria) this;
		}

		public Criteria andValueIdBetween(String value1, String value2) {
			addCriterion("value_id between", value1, value2, "valueId");
			return (Criteria) this;
		}

		public Criteria andValueIdNotBetween(String value1, String value2) {
			addCriterion("value_id not between", value1, value2, "valueId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdIsNull() {
			addCriterion("attribute_id is null");
			return (Criteria) this;
		}

		public Criteria andAttributeIdIsNotNull() {
			addCriterion("attribute_id is not null");
			return (Criteria) this;
		}

		public Criteria andAttributeIdEqualTo(String value) {
			addCriterion("attribute_id =", value, "attributeId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdNotEqualTo(String value) {
			addCriterion("attribute_id <>", value, "attributeId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdGreaterThan(String value) {
			addCriterion("attribute_id >", value, "attributeId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdGreaterThanOrEqualTo(String value) {
			addCriterion("attribute_id >=", value, "attributeId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdLessThan(String value) {
			addCriterion("attribute_id <", value, "attributeId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdLessThanOrEqualTo(String value) {
			addCriterion("attribute_id <=", value, "attributeId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdLike(String value) {
			addCriterion("attribute_id like", value, "attributeId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdNotLike(String value) {
			addCriterion("attribute_id not like", value, "attributeId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdIn(List<String> values) {
			addCriterion("attribute_id in", values, "attributeId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdNotIn(List<String> values) {
			addCriterion("attribute_id not in", values, "attributeId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdBetween(String value1, String value2) {
			addCriterion("attribute_id between", value1, value2, "attributeId");
			return (Criteria) this;
		}

		public Criteria andAttributeIdNotBetween(String value1, String value2) {
			addCriterion("attribute_id not between", value1, value2, "attributeId");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("user_id like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("user_id not like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<String> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<String> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andValueIsNull() {
			addCriterion("value is null");
			return (Criteria) this;
		}

		public Criteria andValueIsNotNull() {
			addCriterion("value is not null");
			return (Criteria) this;
		}

		public Criteria andValueEqualTo(String value) {
			addCriterion("value =", value, "value");
			return (Criteria) this;
		}

		public Criteria andValueNotEqualTo(String value) {
			addCriterion("value <>", value, "value");
			return (Criteria) this;
		}

		public Criteria andValueGreaterThan(String value) {
			addCriterion("value >", value, "value");
			return (Criteria) this;
		}

		public Criteria andValueGreaterThanOrEqualTo(String value) {
			addCriterion("value >=", value, "value");
			return (Criteria) this;
		}

		public Criteria andValueLessThan(String value) {
			addCriterion("value <", value, "value");
			return (Criteria) this;
		}

		public Criteria andValueLessThanOrEqualTo(String value) {
			addCriterion("value <=", value, "value");
			return (Criteria) this;
		}

		public Criteria andValueLike(String value) {
			addCriterion("value like", value, "value");
			return (Criteria) this;
		}

		public Criteria andValueNotLike(String value) {
			addCriterion("value not like", value, "value");
			return (Criteria) this;
		}

		public Criteria andValueIn(List<String> values) {
			addCriterion("value in", values, "value");
			return (Criteria) this;
		}

		public Criteria andValueNotIn(List<String> values) {
			addCriterion("value not in", values, "value");
			return (Criteria) this;
		}

		public Criteria andValueBetween(String value1, String value2) {
			addCriterion("value between", value1, value2, "value");
			return (Criteria) this;
		}

		public Criteria andValueNotBetween(String value1, String value2) {
			addCriterion("value not between", value1, value2, "value");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table uc_user_attr_val
	 * @mbg.generated  Wed Sep 18 02:11:40 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table uc_user_attr_val
     *
     * @mbg.generated do_not_delete_during_merge Mon Sep 16 16:08:22 PHT 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}