package cj.netos.uc.domain;

public class UcUserAttr {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_user_attr.attribute_id
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	private String attributeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_user_attr.name
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_user_attr.segment_id
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	private String segmentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_user_attr.type
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_user_attr.sort
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	private Integer sort;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_user_attr.attribute_id
	 * @return  the value of uc_user_attr.attribute_id
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public String getAttributeId() {
		return attributeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_user_attr.attribute_id
	 * @param attributeId  the value for uc_user_attr.attribute_id
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public void setAttributeId(String attributeId) {
		this.attributeId = attributeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_user_attr.name
	 * @return  the value of uc_user_attr.name
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_user_attr.name
	 * @param name  the value for uc_user_attr.name
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_user_attr.segment_id
	 * @return  the value of uc_user_attr.segment_id
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public String getSegmentId() {
		return segmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_user_attr.segment_id
	 * @param segmentId  the value for uc_user_attr.segment_id
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public void setSegmentId(String segmentId) {
		this.segmentId = segmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_user_attr.type
	 * @return  the value of uc_user_attr.type
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_user_attr.type
	 * @param type  the value for uc_user_attr.type
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_user_attr.sort
	 * @return  the value of uc_user_attr.sort
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_user_attr.sort
	 * @param sort  the value for uc_user_attr.sort
	 * @mbg.generated  Thu Sep 26 21:07:00 PHT 2019
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}
}