package cj.netos.uc.domain;

public class UcUserAttrVal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_attr_val.value_id
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    private String valueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_attr_val.attribute_id
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    private String attributeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_attr_val.user_id
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_attr_val.value
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_attr_val.value_id
     *
     * @return the value of uc_user_attr_val.value_id
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public String getValueId() {
        return valueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_attr_val.value_id
     *
     * @param valueId the value for uc_user_attr_val.value_id
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public void setValueId(String valueId) {
        this.valueId = valueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_attr_val.attribute_id
     *
     * @return the value of uc_user_attr_val.attribute_id
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public String getAttributeId() {
        return attributeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_attr_val.attribute_id
     *
     * @param attributeId the value for uc_user_attr_val.attribute_id
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public void setAttributeId(String attributeId) {
        this.attributeId = attributeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_attr_val.user_id
     *
     * @return the value of uc_user_attr_val.user_id
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_attr_val.user_id
     *
     * @param userId the value for uc_user_attr_val.user_id
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_attr_val.value
     *
     * @return the value of uc_user_attr_val.value
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_attr_val.value
     *
     * @param value the value for uc_user_attr_val.value
     *
     * @mbg.generated Mon Sep 16 16:08:22 PHT 2019
     */
    public void setValue(String value) {
        this.value = value;
    }
}