package cj.netos.uc.domain;

import java.util.Date;

public class UcUserSegment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_user_seg.segment_id
	 * @mbg.generated  Wed Sep 18 02:11:40 CST 2019
	 */
	private String segmentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_user_seg.name
	 * @mbg.generated  Wed Sep 18 02:11:40 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_user_seg.create_time
	 * @mbg.generated  Wed Sep 18 02:11:40 CST 2019
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_user_seg.segment_id
	 * @return  the value of uc_user_seg.segment_id
	 * @mbg.generated  Wed Sep 18 02:11:40 CST 2019
	 */
	public String getSegmentId() {
		return segmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_user_seg.segment_id
	 * @param segmentId  the value for uc_user_seg.segment_id
	 * @mbg.generated  Wed Sep 18 02:11:40 CST 2019
	 */
	public void setSegmentId(String segmentId) {
		this.segmentId = segmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_user_seg.name
	 * @return  the value of uc_user_seg.name
	 * @mbg.generated  Wed Sep 18 02:11:40 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_user_seg.name
	 * @param name  the value for uc_user_seg.name
	 * @mbg.generated  Wed Sep 18 02:11:40 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_user_seg.create_time
	 * @return  the value of uc_user_seg.create_time
	 * @mbg.generated  Wed Sep 18 02:11:40 CST 2019
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_user_seg.create_time
	 * @param createTime  the value for uc_user_seg.create_time
	 * @mbg.generated  Wed Sep 18 02:11:40 CST 2019
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}